### ISSUE TITLE
database.yml doesn't exist

### ISSUE THREAD

**Issue by yumikohey** [bonsaiERP/bonsaiERP#8]
Do I need database.yml to start the app? If not, what should be the first step to setup the app?

Thank you

**Comment by gizmore** [comment]
Am 28.10.2016 um 07:55 schrieb Yumiko Huang:
> Do I need database.yml to start the app? If not, what should be the first step to setup the app?
>
> Thank you
>
    bundle install --path vendor/bundle # Optional

    bundle update

For Rails apps:

    bundle exec rake db:migrate # Typos?

    bundle exec rake db:seed # Typos?

    bundle exec rake assets:precompile # Typos?


I might have typo somewhere, but you can google better now :)


Cheers

gizmore

**Comment by steveroot** [comment]
database.yml is missing, I created one for myself like;

```
development:
  adapter: postgresql
  encoding: unicode
  database: bonsai_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: bonsai_test
  pool: 5
```

production to be added once I have everything working in development (but probably only on the server, no need to keep username and passwords in a git repo)
